//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireSockUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WireSockUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string AddProfileExistsMsg {
            get {
                return ResourceManager.GetString("AddProfileExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import error.
        /// </summary>
        internal static string AddProfileExistsTitle {
            get {
                return ResourceManager.GetString("AddProfileExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of WireSockUI or Wiresock VPN Client Service is already running..
        /// </summary>
        internal static string AlreadyRunningMessage {
            get {
                return ResourceManager.GetString("AlreadyRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Running.
        /// </summary>
        internal static string AlreadyRunningTitle {
            get {
                return ResourceManager.GetString("AlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock needs to be installed for WireSockUI to function..
        /// </summary>
        internal static string AppNoWireSockMessage {
            get {
                return ResourceManager.GetString("AppNoWireSockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock not found.
        /// </summary>
        internal static string AppNoWireSockTitle {
            get {
                return ResourceManager.GetString("AppNoWireSockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer WireSockUI client is available for download..
        /// </summary>
        internal static string AppUpdateMessage {
            get {
                return ResourceManager.GetString("AppUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string AppUpdateTitle {
            get {
                return ResourceManager.GetString("AppUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.wiresock.net/.
        /// </summary>
        internal static string AppWireSockURL {
            get {
                return ResourceManager.GetString("AppWireSockURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating... Click to Cancel.
        /// </summary>
        internal static string ButtonActivating {
            get {
                return ResourceManager.GetString("ButtonActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string ButtonActive {
            get {
                return ResourceManager.GetString("ButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ButtonInactive {
            get {
                return ResourceManager.GetString("ButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Active.
        /// </summary>
        internal static string ContextMenuActive {
            get {
                return ResourceManager.GetString("ContextMenuActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Inactive.
        /// </summary>
        internal static string ContextMenuInactive {
            get {
                return ResourceManager.GetString("ContextMenuInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove profile &quot;{0}&quot;?.
        /// </summary>
        internal static string DeleteProfileConfirmMsg {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string DeleteProfileConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect on start.
        /// </summary>
        internal static string DialogAutoConnect {
            get {
                return ResourceManager.GetString("DialogAutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireguard configuration files (*.conf)|*.conf.
        /// </summary>
        internal static string DialogOpenFileFilter {
            get {
                return ResourceManager.GetString("DialogOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select configuration file.
        /// </summary>
        internal static string DialogOpenFileTitle {
            get {
                return ResourceManager.GetString("DialogOpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditCancel {
            get {
                return ResourceManager.GetString("EditCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes....
        /// </summary>
        internal static string EditProcesses {
            get {
                return ResourceManager.GetString("EditProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter profile name....
        /// </summary>
        internal static string EditProfileCue {
            get {
                return ResourceManager.GetString("EditProfileCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error.
        /// </summary>
        internal static string EditProfileError {
            get {
                return ResourceManager.GetString("EditProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name missing or invalid.
        /// </summary>
        internal static string EditProfileNameError {
            get {
                return ResourceManager.GetString("EditProfileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing configuration {0}.
        /// </summary>
        internal static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New configuration.
        /// </summary>
        internal static string EditProfileTitleNew {
            get {
                return ResourceManager.GetString("EditProfileTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key:.
        /// </summary>
        internal static string EditPublicKey {
            get {
                return ResourceManager.GetString("EditPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock UI.
        /// </summary>
        internal static string FormMain {
            get {
                return ResourceManager.GetString("FormMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string FormSettings {
            get {
                return ResourceManager.GetString("FormSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select process.
        /// </summary>
        internal static string FormTaskManager {
            get {
                return ResourceManager.GetString("FormTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string InterfaceAddresses {
            get {
                return ResourceManager.GetString("InterfaceAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTU.
        /// </summary>
        internal static string InterfaceMTU {
            get {
                return ResourceManager.GetString("InterfaceMTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        internal static string InterfacePublicKey {
            get {
                return ResourceManager.GetString("InterfacePublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string InterfaceStatus {
            get {
                return ResourceManager.GetString("InterfaceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string InterfaceStatusActive {
            get {
                return ResourceManager.GetString("InterfaceStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string InterfaceStatusInactive {
            get {
                return ResourceManager.GetString("InterfaceStatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface: {0}.
        /// </summary>
        internal static string InterfaceTitle {
            get {
                return ResourceManager.GetString("InterfaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last saved config not found..
        /// </summary>
        internal static string LastProfileNotFound {
            get {
                return ResourceManager.GetString("LastProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.fff.
        /// </summary>
        internal static string LogTimestampFormat {
            get {
                return ResourceManager.GetString("LogTimestampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tunnel.
        /// </summary>
        internal static string MenuAddTunnel {
            get {
                return ResourceManager.GetString("MenuAddTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tunnel.
        /// </summary>
        internal static string MenuDeleteTunnel {
            get {
                return ResourceManager.GetString("MenuDeleteTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty tunnel....
        /// </summary>
        internal static string MenuEmptyTunnel {
            get {
                return ResourceManager.GetString("MenuEmptyTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tunnel from file....
        /// </summary>
        internal static string MenuImportTunnel {
            get {
                return ResourceManager.GetString("MenuImportTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer.
        /// </summary>
        internal static string PanelPeer {
            get {
                return ResourceManager.GetString("PanelPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PanelState {
            get {
                return ResourceManager.GetString("PanelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed apps.
        /// </summary>
        internal static string PeerAllowedApps {
            get {
                return ResourceManager.GetString("PeerAllowedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed IPs.
        /// </summary>
        internal static string PeerAllowedIPs {
            get {
                return ResourceManager.GetString("PeerAllowedIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallowed apps.
        /// </summary>
        internal static string PeerDisallowedApps {
            get {
                return ResourceManager.GetString("PeerDisallowedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallowed IPs.
        /// </summary>
        internal static string PeerDisallowedIPs {
            get {
                return ResourceManager.GetString("PeerDisallowedIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        internal static string PeerEndpoint {
            get {
                return ResourceManager.GetString("PeerEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent keepalive.
        /// </summary>
        internal static string PeerPersistentKeepAlive {
            get {
                return ResourceManager.GetString("PeerPersistentKeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preshared key.
        /// </summary>
        internal static string PeerPresharedKey {
            get {
                return ResourceManager.GetString("PeerPresharedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string PeerPresharedKeyValue {
            get {
                return ResourceManager.GetString("PeerPresharedKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        internal static string PeerPublicKey {
            get {
                return ResourceManager.GetString("PeerPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS5 password.
        /// </summary>
        internal static string PeerSocks5Password {
            get {
                return ResourceManager.GetString("PeerSocks5Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configured.
        /// </summary>
        internal static string PeerSocks5PasswordValue {
            get {
                return ResourceManager.GetString("PeerSocks5PasswordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS5 proxy.
        /// </summary>
        internal static string PeerSocks5Proxy {
            get {
                return ResourceManager.GetString("PeerSocks5Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS5 Username.
        /// </summary>
        internal static string PeerSocks5Username {
            get {
                return ResourceManager.GetString("PeerSocks5Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search....
        /// </summary>
        internal static string ProcessesSearchCue {
            get {
                return ResourceManager.GetString("ProcessesSearchCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile error.
        /// </summary>
        internal static string ProfileError {
            get {
                return ResourceManager.GetString("ProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Network Adapter mode.
        /// </summary>
        internal static string SettingsAdapterMode {
            get {
                return ResourceManager.GetString("SettingsAdapterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically connect on start.
        /// </summary>
        internal static string SettingsAutoConnect {
            get {
                return ResourceManager.GetString("SettingsAutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray on start.
        /// </summary>
        internal static string SettingsAutoMinimize {
            get {
                return ResourceManager.GetString("SettingsAutoMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run when Windows starts.
        /// </summary>
        internal static string SettingsAutoRun {
            get {
                return ResourceManager.GetString("SettingsAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check online for updates.
        /// </summary>
        internal static string SettingsAutoUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level.
        /// </summary>
        internal static string SettingsLogLevel {
            get {
                return ResourceManager.GetString("SettingsLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open profiles folder.
        /// </summary>
        internal static string SettingsProfiles {
            get {
                return ResourceManager.GetString("SettingsProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string SizeBytes {
            get {
                return ResourceManager.GetString("SizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} {1}.
        /// </summary>
        internal static string SizeFormat {
            get {
                return ResourceManager.GetString("SizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiB.
        /// </summary>
        internal static string SizeGB {
            get {
                return ResourceManager.GetString("SizeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        internal static string SizeKB {
            get {
                return ResourceManager.GetString("SizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        internal static string SizeMB {
            get {
                return ResourceManager.GetString("SizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiB.
        /// </summary>
        internal static string SizePB {
            get {
                return ResourceManager.GetString("SizePB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiB.
        /// </summary>
        internal static string SizeTB {
            get {
                return ResourceManager.GetString("SizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest handshake.
        /// </summary>
        internal static string StateHandshake {
            get {
                return ResourceManager.GetString("StateHandshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated loss.
        /// </summary>
        internal static string StateLoss {
            get {
                return ResourceManager.GetString("StateLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string StateLossValue {
            get {
                return ResourceManager.GetString("StateLossValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round-trip time.
        /// </summary>
        internal static string StateRTT {
            get {
                return ResourceManager.GetString("StateRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ms.
        /// </summary>
        internal static string StateRTTValue {
            get {
                return ResourceManager.GetString("StateRTTValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string StateTransfer {
            get {
                return ResourceManager.GetString("StateTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} received, {1} sent.
        /// </summary>
        internal static string StateTransferValue {
            get {
                return ResourceManager.GetString("StateTransferValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string TabPageLog {
            get {
                return ResourceManager.GetString("TabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnels.
        /// </summary>
        internal static string TabPageTunnels {
            get {
                return ResourceManager.GetString("TabPageTunnels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///# WireGuard sample configuration, please provide the necessary details
        ///#
        ///; Local Interface Definition
        ///[Interface]
        ///PrivateKey = 
        ///; Local address in CIDR format
        ///Address = 172.16.0.2/32
        ///MTU = 1280
        ///DNS = 1.0.0.1, 1.1.1.1
        ///
        ///; Peer Definition
        ///[Peer]
        ///PublicKey = 
        ///; Optional: preshared key
        ///PresharedKey = 
        ///; Peer IPv4, IPv6 or DNS endpoint with port
        ///Endpoint = myserver.dyndns.org:51820
        ///AllowedIPs = 0.0.0.0/0, ::/0
        ///; Optional: Send persistent keep alive packets every 5 minutes (900 sec)
        ///Persisten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_conf {
            get {
                return ResourceManager.GetString("template.conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string TimeLapseDay {
            get {
                return ResourceManager.GetString("TimeLapseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days ago.
        /// </summary>
        internal static string TimeLapseDays {
            get {
                return ResourceManager.GetString("TimeLapseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        internal static string TimeLapseHour {
            get {
                return ResourceManager.GetString("TimeLapseHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours ago.
        /// </summary>
        internal static string TimeLapseHours {
            get {
                return ResourceManager.GetString("TimeLapseHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        internal static string TimeLapseMinute {
            get {
                return ResourceManager.GetString("TimeLapseMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes ago.
        /// </summary>
        internal static string TimeLapseMinutes {
            get {
                return ResourceManager.GetString("TimeLapseMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        internal static string TimeLapseMonth {
            get {
                return ResourceManager.GetString("TimeLapseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  months ago.
        /// </summary>
        internal static string TimeLapseMonths {
            get {
                return ResourceManager.GetString("TimeLapseMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        internal static string TimeLapseSecond {
            get {
                return ResourceManager.GetString("TimeLapseSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds ago.
        /// </summary>
        internal static string TimeLapseSeconds {
            get {
                return ResourceManager.GetString("TimeLapseSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year ago.
        /// </summary>
        internal static string TimeLapseYear {
            get {
                return ResourceManager.GetString("TimeLapseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years ago.
        /// </summary>
        internal static string TimeLapseYears {
            get {
                return ResourceManager.GetString("TimeLapseYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} tunnel has been activated..
        /// </summary>
        internal static string ToastActiveMessage {
            get {
                return ResourceManager.GetString("ToastActiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock Activated.
        /// </summary>
        internal static string ToastActiveTitle {
            get {
                return ResourceManager.GetString("ToastActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} tunnel has been deactivated..
        /// </summary>
        internal static string ToastInactiveMessage {
            get {
                return ResourceManager.GetString("ToastInactiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock Deactivated.
        /// </summary>
        internal static string ToastInactiveTitle {
            get {
                return ResourceManager.GetString("ToastInactiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock: Activating.
        /// </summary>
        internal static string TrayActivating {
            get {
                return ResourceManager.GetString("TrayActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock: Active.
        /// </summary>
        internal static string TrayActive {
            get {
                return ResourceManager.GetString("TrayActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireSock: Inactive.
        /// </summary>
        internal static string TrayInactive {
            get {
                return ResourceManager.GetString("TrayInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the tunnel from the provided configuration. Please check log..
        /// </summary>
        internal static string TunnelErrorCreate {
            get {
                return ResourceManager.GetString("TunnelErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to tunnel manager. Please check log..
        /// </summary>
        internal static string TunnelErrorManager {
            get {
                return ResourceManager.GetString("TunnelErrorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel has failed to start. Please check log..
        /// </summary>
        internal static string TunnelErrorStart {
            get {
                return ResourceManager.GetString("TunnelErrorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TunnelErrorTitle {
            get {
                return ResourceManager.GetString("TunnelErrorTitle", resourceCulture);
            }
        }
    }
}
